/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AnnotateAssignmentIdRouteImport } from './routes/annotate.$assignmentId'
import { Route as AdminVideosRouteImport } from './routes/admin/videos'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminVideoVideoIdRouteImport } from './routes/admin/video.$videoId'
import { Route as AdminFrameFrameIdRouteImport } from './routes/admin/frame.$frameId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AnnotateAssignmentIdRoute = AnnotateAssignmentIdRouteImport.update({
  id: '/annotate/$assignmentId',
  path: '/annotate/$assignmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVideoVideoIdRoute = AdminVideoVideoIdRouteImport.update({
  id: '/video/$videoId',
  path: '/video/$videoId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFrameFrameIdRoute = AdminFrameFrameIdRouteImport.update({
  id: '/frame/$frameId',
  path: '/frame/$frameId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/annotate/$assignmentId': typeof AnnotateAssignmentIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/frame/$frameId': typeof AdminFrameFrameIdRoute
  '/admin/video/$videoId': typeof AdminVideoVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/annotate/$assignmentId': typeof AnnotateAssignmentIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/frame/$frameId': typeof AdminFrameFrameIdRoute
  '/admin/video/$videoId': typeof AdminVideoVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/annotate/$assignmentId': typeof AnnotateAssignmentIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/frame/$frameId': typeof AdminFrameFrameIdRoute
  '/admin/video/$videoId': typeof AdminVideoVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/admin/reviews'
    | '/admin/users'
    | '/admin/videos'
    | '/annotate/$assignmentId'
    | '/admin/'
    | '/admin/frame/$frameId'
    | '/admin/video/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/admin/reviews'
    | '/admin/users'
    | '/admin/videos'
    | '/annotate/$assignmentId'
    | '/admin'
    | '/admin/frame/$frameId'
    | '/admin/video/$videoId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/admin/reviews'
    | '/admin/users'
    | '/admin/videos'
    | '/annotate/$assignmentId'
    | '/admin/'
    | '/admin/frame/$frameId'
    | '/admin/video/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AnnotateAssignmentIdRoute: typeof AnnotateAssignmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/annotate/$assignmentId': {
      id: '/annotate/$assignmentId'
      path: '/annotate/$assignmentId'
      fullPath: '/annotate/$assignmentId'
      preLoaderRoute: typeof AnnotateAssignmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/video/$videoId': {
      id: '/admin/video/$videoId'
      path: '/video/$videoId'
      fullPath: '/admin/video/$videoId'
      preLoaderRoute: typeof AdminVideoVideoIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/frame/$frameId': {
      id: '/admin/frame/$frameId'
      path: '/frame/$frameId'
      fullPath: '/admin/frame/$frameId'
      preLoaderRoute: typeof AdminFrameFrameIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVideosRoute: typeof AdminVideosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminFrameFrameIdRoute: typeof AdminFrameFrameIdRoute
  AdminVideoVideoIdRoute: typeof AdminVideoVideoIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminReviewsRoute: AdminReviewsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVideosRoute: AdminVideosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminFrameFrameIdRoute: AdminFrameFrameIdRoute,
  AdminVideoVideoIdRoute: AdminVideoVideoIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AnnotateAssignmentIdRoute: AnnotateAssignmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
